/**
 * The generated file has to open by importing the module it augments.
 *
 * Without it `declare module` shadows the module rather than adding to it, and
 * every import of the SDK stops resolving with an error naming the missing
 * export rather than the file that hid it.
 */
const PREAMBLE = [
  "// Generated by `anpord generate`. Do not edit.",
  "// Run it again after changing which variables a prompt uses.",
  'import "anpord";',
  "",
  'declare module "anpord" {',
  "  interface AnpordPromptVariables {",
].join("\n");

/** Quoted, because an id may carry characters an identifier cannot. */
const entry = (id: string, names: readonly string[]) => {
  const shape =
    names.length === 0
      ? "Record<string, never>"
      : `{ ${names.map((name) => `"${name}": string`).join("; ")} }`;

  return `    "${id}": ${shape};`;
};

export const declarationFile = (
  prompts: readonly (readonly [string, readonly string[]])[]
) =>
  [
    PREAMBLE,
    ...[...prompts]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([id, names]) => entry(id, names)),
    "  }",
    "}",
    "",
  ].join("\n");
