export const ANSWER_ENV = "ANPORD_ANSWER_FILE";

export const TRANSCRIPT_ENV = "ANPORD_TRANSCRIPT_FILE";

export const TURNS_ENV = "ANPORD_TURNS_FILE";

export const PREPARE_VALUE_ENV = "ANPORD_PREPARE_VALUE";

export const CACHE_RESTORED_ENV = "ANPORD_CACHE_RESTORED";

export const PREPARE_RESULT_MARKER = "ANPORD_PREPARE_RESULT=";
