export const ANSWER_ENV = "SPHYNX_ANSWER_FILE";

export const TRANSCRIPT_ENV = "SPHYNX_TRANSCRIPT_FILE";

export const TURNS_ENV = "SPHYNX_TURNS_FILE";

export const PREPARE_VALUE_ENV = "SPHYNX_PREPARE_VALUE";

export const CACHE_RESTORED_ENV = "SPHYNX_CACHE_RESTORED";

export const PREPARE_RESULT_MARKER = "SPHYNX_PREPARE_RESULT=";
